[phases.setup]
nixPkgs = ["nodejs_20", "python3", "python3Packages.pip"]

[phases.install]
cmds = ["python3 -m pip install --upgrade yt-dlp --break-system-packages", "npm install"]

[start]
cmd = "node proxy.js"